### ISSUE TITLE
How to run benchmark prog?

### ISSUE THREAD

**Issue by ghost** [libinzhangyuan/asio_kcp#1]
@libinzhangyuan 
Happy to see your code. 
I need to persistent real send data from USA to China.
So I want to run bench mark first to see the speed.
I checkout tag **kcp_bench_mark_test** but didn't see **asio_kcp_server** and **asio_kcp_client**. 
Is there anything I did wrong?
Need your help!
Thank you very much!

**Comment by libinzhangyuan** [comment]
You will find the file after compiling.
Just follow the doc.
