### ISSUE TITLE
启动即崩溃：/lib64/libpthread.so.0

### ISSUE THREAD

**Issue by LazyPlanet** [libinzhangyuan/asio_kcp#10]
[game@VM_109_84_centos server]$ ./server 0.0.0.0 12345
FILE ERROR:  could not open log file:[/var/log/asio_kcp_log/server.g2log.20180209-114600.log]
                 std::ios_base state = 4
Cannot write logfile to location, attempting current directory

***** FATAL TRIGGER RECEIVED ******* 
Received fatal signal: SIGSEGV(11)
        PID: 15238
        stack dump [1]  /lib64/libpthread.so.0+0xf370 [0x7f36bbd7e370]
        stack dump [2]  /lib64/libc.so.6setbuffer+0x7 [0x7f36bba1b597]
        stack dump [3]  ./server() [0x43e0c0]
        stack dump [4]  ./server() [0x43e1f6]
        stack dump [5]  ./server() [0x41901e]
        stack dump [6]  /lib64/libc.so.6__libc_start_main+0xf5 [0x7f36bb9cfb35]
        stack dump [7]  ./server() [0x4074b4]

***** RETHROWING SIGNAL SIGSEGV(11)

g2log exiting after receiving fatal event
Log file at: [./server.g2log.20180209-114600.log]

Exiting - FATAL SIGNAL: 11   段错误

**系统版本**
[game@VM_109_84_centos server]$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)
**GCC/G++版本**
[game@VM_109_84_centos server]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

谢谢作者。

**Comment by libinzhangyuan** [comment]
光是这样，我也没法判断为什么。

不过报错里面说无法创建 /var/log/asio_kcp_log/server.g2log.20180209-114600.log
你看看是否目录存在 /var/log/asio_kcp_log/

**Comment by LazyPlanet** [comment]
即使我改了日志，让他正常生成也是有问题的，主要是core直接崩没有了，啥都看不了。我运行的就是您的demo，没改东西。
