### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by dongguadan** [libinzhangyuan/asio_kcp#3]
Hi, i have ran the asio_kcp in centos. But i found there is memory leak from server_lib. Do you know what may cause this...  thanks!

---

[root@ ~]# free
             total       used       free     shared    buffers     cached
Mem:       1922244     237748    1684496          0      12260     155564
-/+ buffers/cache:      69924    1852320
Swap:            0          0          0
[root@ ~]# free
             total       used       free     shared    buffers     cached
Mem:       1922244     238104    1684140          0      12268     155972
-/+ buffers/cache:      69864    1852380
Swap:            0          0          0
[root@ ~]# free
             total       used       free     shared    buffers     cached
Mem:       1922244     250132    1672112          0      12532     167364
-/+ buffers/cache:      70236    1852008
Swap:            0          0          0

**Comment by libinzhangyuan** [comment]
Sorry for delay. I find your message today.

This code lack one of feature "release the connection".
There are some api defined in server.hpp which was commented. And it's not finished.
I'll finish the code later.

```
// eDisconnect return when none msg recved within mtime milliseconds.
//   or after you calling force_disconnect.
//  void set_diconnect_time(uint32_t mtime);

// eLagNotify return when none msg recved within mtime milliseconds.
// eLagNotify will be not returned if you do not set this or set this 0.
//  void set_lag_notify_time(uint32_t mtime);

//  int send_msg(const kcp_conv_t& conv, std::shared_ptr<std::string> msg);
//  int send_msg(const std::vector< kcp_conv_t conv >& /*convs*/, std::shared_ptr<std::string> msg);
//  int send_msg_to_all();                                                                                                                        
//  void force_disconnect(const kcp_conv_t& conv);
```

**Comment by libinzhangyuan** [comment]
complete the disconnect when timeout longtime.
