### ISSUE TITLE
how to filter log？ why so much log？

### ISSUE THREAD

**Issue by zuowanbushiwo** [libinzhangyuan/asio_kcp#8]
like this log，how this log is closed？ thanks！
@asio|1508310907.245388|168|deadline_timer@0x1917b30.cancel
@asio|1508310907.245393|168*169|deadline_timer@0x1917b30.async_wait
@asio|1508310907.245400|<245400|
@asio|1508310907.250925|>169|ec=system:0
@asio|1508310907.250940|169|deadline_timer@0x1917b30.cancel
@asio|1508310907.250944|169*170|deadline_timer@0x1917b30.async_wait
@asio|1508310907.250949|<250949|
@asio|1508310907.256449|>170|ec=system:0
@asio|1508310907.256466|170|deadline_timer@0x1917b30.cancel
@asio|1508310907.256471|170*171|deadline_timer@0x1917b30.async_wait
@asio|1508310907.256476|<256476|
@asio|1508310907.261937|>171|ec=system:0
@asio|1508310907.261954|171|deadline_timer@0x1917b30.cancel
@asio|1508310907.261958|171*172|deadline_timer@0x1917b30.async_wait
@asio|1508310907.261963|<261963|
@asio|1508310907.267578|>172|ec=system:0
@asio|1508310907.267609|172|deadline_timer@0x1917b30.cancel
@asio|1508310907.267615|172*173|deadline_timer@0x1917b30.async_wait
@asio|1508310907.267621|<267621|
@asio|1508310907.273136|>173|ec=system:0
@asio|1508310907.273152|173|deadline_timer@0x1917b30.cancel
@asio|1508310907.273156|173*174|deadline_timer@0x1917b30.async_wait
@asio|1508310907.273161|<273161|
@asio|1508310907.278537|>174|ec=system:0

**Comment by libinzhangyuan** [comment]
just like this,
./server/server 0.0.0.0 12345 2>&1 | grep --line-buffered -v -e deadline_timer -e "ec=system:0$" -e "|$" >>bserver.txt
or
./server/server 0.0.0.0 12345 2>&1 | grep --line-buffered -v -e deadline_timer -e "ec=system:0$" -e "|$" -e "@asio" >>bserver.txt

then
    tail -f bserver.txt

**Comment by zuowanbushiwo** [comment]
@libinzhangyuan 
thanks ， I still have a problem： Do ikcpcb need to release resources at the end?

**Comment by libinzhangyuan** [comment]
Yes.  It's released in server_lib. But won't be released in client_lib currently.
I will finish client code later.

**Comment by libinzhangyuan** [comment]
released ikcpcb in client_lib already.
